services:
  db:
    image: postgres:16
    restart: always
    container_name: qualitrace-db
    environment:
      POSTGRES_DB: qualitrace
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: devtime-redis
    ports:
      - "6379:6379"
    networks:
      - qualitrace_network

volumes:
  postgres_data:

networks:
  qualitrace_network:
    driver: bridge